### ISSUE TITLE
About configuration

### ISSUE THREAD

**Issue by tanyue2019** [rajbsk/KG-conv-rec#1]
Hello, thank you very much for your open source code！
I would like to ask whether the version of pytorch has a big impact on the operation? I noticed that the pytorch official website no longer provides the installation of version 1.3.0
Looking forward to your reply

**Comment by rajbsk** [comment]
Hi!
While working on the code, the combination of python modules provided was the most stable. I had to work around a lot of dependency errors until I could find a stable configuration for all the python module. Can you try installing torch 1.3.0 with cuda 10.1 and see if that works.
Thanks,
Rajdeep

**Comment by tanyue2019** [comment]
Thank you. I see. Thank you very much for your reply
